name: Build and create release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build        
        ls -al build/
        ls -al .
        ls -al ../
        ls -al ../../
        ls -al ../../../
    - name: upload build
      uses: actions/upload-artifact@v4
      with:
        name: osp-chrome-ext
        path: ./build/**/*
